### ISSUE TITLE
Nextjs に Google Analytics を導入すると 「TypeError: window.gtag is not a function」というエラーが出る

### ISSUE THREAD

**Issue by KushibikiMashu** [KushibikiMashu/my-tech-blog#4]
![image](https://user-images.githubusercontent.com/36080801/132317658-06413bba-4673-46a1-8a58-1dc941d47bc1.png)

https://twitter.com/ru88s/status/1435089206188015620

**Comment by KushibikiMashu** [comment]
考えられる原因

1. サーバー側で pageview を呼び出している

window の存在チェックを追加する


```js
if (typeof window !== 'undefined') {
  window.gtag("config", GA_TRACKING_ID, {
    page_location: url,
  });
}
```

https://stackoverflow.com/a/62797559

-----

自分の環境では再現しませんでした 😅

一旦、もし可能ならバグが再現するレポジトリを用意してもらうか、 [Next.js + Google Analytics の最小構成でエラーが出ないレポジトリを作った](https://github.com/KushibikiMashu/nextjs-google-analytics)ので、設定ファイルなどを比較してもらうかしてもらっていいでしょうか？

**Comment by KushibikiMashu** [comment]
自分の環境だと PhpStorm で型定義のファイルにジャンプできます

<img width="759" alt="スクリーンショット 2021-09-07 16 10 04" src="https://user-images.githubusercontent.com/36080801/132319306-d39f3338-64f0-4282-8d0a-3d20e0600b88.png">

<img width="858" alt="スクリーンショット 2021-09-07 16 10 14" src="https://user-images.githubusercontent.com/36080801/132319325-398fda9d-764e-4a3a-b9e7-4e644973183f.png">

**Comment by ru88s** [comment]
再現しなかったのですね！お手数おかけして申し訳ないです。
こちらでも型定義のファイルにジャンプできるのを確認できました。
用意していただいたレポジトリと比較させていただきます。
本当に有難うございます！

<img width="664" alt="スクリーンショット 2021-09-07 18 25 49" src="https://user-images.githubusercontent.com/42270511/132320595-42e2662b-39f2-46a7-8064-1623eae1b7d0.png">

**Comment by KushibikiMashu** [comment]
はい、また原因分かりましたら共有していただけると嬉しいです！

**Comment by ru88s** [comment]
TypeError: window.gtag is not a function」のエラーがでるのはページ遷移時でした。
共有できておらず申し訳ないです。

作成していただいたレポジトリを元にページ遷移を試したのですが、なぜかhandleRouteChangeの中にいかないようでした。

<img width="524" alt="スクリーンショット 2021-09-07 19 18 22" src="https://user-images.githubusercontent.com/42270511/132328551-f002fb0d-b273-4b11-9d2c-cb3d7845311b.png">

https://gyazo.com/b1efc679922173c6ee9025de65d8d295

https://github.com/ru88s/nextjs-google-analytics

**Comment by ru88s** [comment]
<img width="835" alt="スクリーンショット 2021-09-07 19 28 42" src="https://user-images.githubusercontent.com/42270511/132329924-69f6c671-c204-42cc-8551-8820df2743ba.png">

無理やり`pageview("test")`をするとエラーが再現できました。

**Comment by KushibikiMashu** [comment]
手元で再現しました！調べてみますー

**Comment by KushibikiMashu** [comment]
原因わかりました！

こちら、Script コンポーネントは`_document.tsx` ではなく `_app.tsx`で読み込むように変わったのを記事に反映してませんでした 🙏 

```ts
// _app.tsx
function MyApp({ Component, pageProps }: AppProps) {
  usePageView()

  return (
    <>
      <Script defer src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`} strategy="afterInteractive" />
      <Script id="ga" defer strategy="afterInteractive">
        {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());    
              gtag('config', '${GA_ID}');
          `}
      </Script>

      <Component {...pageProps} />
    </>
  )
}
```

このように書くと動作するようになりました！

![スクリーンショット 2021-09-07 20 11 06](https://user-images.githubusercontent.com/36080801/132335597-c3337f17-f990-4f47-b4fc-97457be598bd.png)

![スクリーンショット 2021-09-07 20 11 28](https://user-images.githubusercontent.com/36080801/132335602-b1e25ce4-a09e-463a-9de9-a82304cfd05f.png)
